/*
 389. Find the Difference
Easy
Topics
Companies
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.



Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"


Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
 */

#include <algorithm>
#include <iostream>
#include <ranges>

class Solution {
   public:
    char findTheDifference(std::string s, std::string t) {
        if (!std::ranges::is_sorted(s)) {
            std::ranges::sort(s);
        }
        if (!std::ranges::is_sorted(t)) {
            std::ranges::sort(t);
        }
        ssize_t size_long_word = t.size();
        ssize_t size_short_word = s.size();
        char symbol = 0;
        std::ranges::for_each(std::views::iota(0) | std::views::take(size_long_word),
                              [&s, &t, &symbol, &size_short_word](auto const& i) {
                                  if (symbol == 0) {
                                      if(s[i] != t[i]){
                                          symbol = t[i];
                                      }
                                      if (symbol == 0 and i == size_short_word) {
                                          symbol = t[i];
                                      }
                                  }
                              });
        return symbol;
    }
};

int main() {
    Solution sol;
//    char result = sol.findTheDifference("abcd", "abcde");
//    char result = sol.findTheDifference("", "y");
    char result = sol.findTheDifference("ae", "aea");
    std::cout << result << std::endl;
}
